server:
  port: 8088


spring:
  servlet:
    multipart:
      #单次请求 所有文件的大小的总和
      max-request-size: 100MB
      #单个文件的大小
      max-file-size: 10MB
  mvc:
    #文件的访问路径 http://localhost:8088/image/123.png
    static-path-pattern: /image/**
    web:
      resources:
        #文件的保存路径，classpath 指resource文件夹以下
        static-locations: classpath:ImageFiles
        #      static-locations: file:E:/StuProject/IDEAProject/SpringBoot-Image/Image
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/workspace?serverTimezone=GMT
    username: root
    password: 106320


mybatis-plus:
  # 扫描 resoueces下的mapper.xml文件
  mapper-locations:
    - classpath*:mapper/*.xml
  # 实体类存放位置，好像不写也行
  #type-aliases-package: org.work.space.entity
  # 打印sql日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
